name: Deploy docker image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall sqlx-cli cargo-make --no-confirm

      - name: Cache Rust dependencies
        uses: useblacksmith/rust-cache@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: cargo make build_image

      - name: Upload image
        run: docker push ghcr.io/Brodino96/discord_temp:latest